### ISSUE TITLE
Create Game page with falling words to be typed

### ISSUE THREAD

**Issue by phatyma** [chingu-voyages/v36-toucans-team-04#13]
As a player,
I want to see a functioning game screen
So that I can play the game

I want to see:

- [ ] ~~A prompt at the start to enter my name - The application will address me by the name I provide throughout the game (For example: "Hello, [NAME], the game will start soon!", "[Name], the game has ended, here is your game summary.").~~
- [x] A textbox to indicate player's WPM
- [ ] ~~A Start/Stop button~~
- [x] Random words falling from the top of the page to the bottom when the game starts
- [x] Hearts that represent the number of Lives that I have. A heart can represent one life. If I fail to type a word, I would see one of the hearts on the game screen disappear.
- [x] A running score while I play the game

**Comment by phatyma** [comment]
As a player I want to see:
A prompt at the start to enter my name

**Comment by mpark4656** [comment]
We discussed that the pause button will not be available to players during the game.

**Comment by mpark4656** [comment]
Prompting for player name will not be implemented.
