### ISSUE TITLE
Apply Rule - Words failed to be typed are removed and updates lives

### ISSUE THREAD

**Issue by phatyma** [chingu-voyages/v36-toucans-team-04#16]
As a player
When I fail to type a word and it hits the bottom, I want the word to disappear and number of lives I have is decreased by 1
So that I confirm that I failed to type the word

**Comment by sorensoroush** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Chingu-Voyage-36---Toucans-Team-04-61d5d630f218860011303477/issues/chingu-voyages/v36-toucans-team-04/16?planning-poker) with ZenHub @mpark4656
